version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/guajojo-frontend:cached
      - ../../shared-types:/workspaces/shared-types
    command: sleep infinity


